# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            mTRAC
tagline:          'Mobile technology-rich active classroom'
description:      'Mobile Technology-Rich Active Classroom'
url:              / # https://gordontang.github.io/mTRAC-site/

author:
  name:           'Gordon Tang'
  url:            

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/gordontang/mTRAC-site
