# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            mTRAC
tagline:          'Mobile Technology-Rich Active Classroom'
description:      'Mobile Technology-Rich Active Classroom'
url:              https://gordontang.github.io/mTRAC-site
baseurl:          https://gordontang.github.io/mTRAC-site/

author:
  name:           'Gordon Tang'
  url:            

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/gordontang/mTRAC-site
